[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "/Library/Frameworks/Python.framework/Versions/3.12/bin/solc"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
